config/routes.rb
Rails.application.routes.draw do
  get '/tasks/completed' => 'tasks#completed'
  
  resources :tasks
  resources :projects do
    resources :tasks, only: [:new]
  end
  resources :friendships, only: [:new, :create, :destroy]
  resources :comments, only: [:create, :destroy]
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: [:index, :show] do
    resources :projects, only: [:index]
  end

  authenticated :user do
    root 'projects#index', as: 'authenticated_root'
  end
  devise_scope :user do
    root 'devise/sessions#new'
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true

  validates :user_id, :content, presence: true
  validates :commentable, presence: true

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        @comment = Comment.new(comment_params)
        if @comment.commentable_type == "Task" && @comment.save
            flash[:success] = "Your comment has been added"
            redirect_to task_path(@comment.commentable_id)
        elsif @comment.commentable_type == "Project" && @comment.save
            flash[:success] = "Your comment has been added"
            redirect_to project_path(@comment.commentable_id)
        else
            flash[:error] = "Something went wrong! Please try again."
            session[:return_to] ||= request.referer
            redirect_to session.delete(:return_to)
        end
    end

    def destroy  
        @comment = Comment.find_by(id: params[:id])
        @comment.destroy
        session[:return_to] ||= request.referer
        redirect_to session.delete(:return_to)
    end

    private

    def comment_params
        params.require(:comment).permit(:content, :user_id, :commentable_type, :commentable_id)
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<hr>
<h5>Comments</h5>

<% object.comments.each do |comment| %>
    Comment from <%= link_to comment.user.full_name, user_projects_path(comment.user) %>: <br>
    <%= comment.content %>
    <% if comment.user == current_user %>
        <%= button_to "Delete Comment", comment_path(comment), method: :delete %>
    <% end %> <br><br>
<% end %>

<%= form_for @comment do |f| %>
    <%= f.hidden_field :commentable_type, value: object.class.to_s %>
    <%= f.hidden_field :commentable_id, value: object.id %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.label :content, "New Comment" %>
    <%= f.text_area :content %>
    <%= f.submit %>
<% end %>