config/routes.rb
Rails.application.routes.draw do
  get '/tasks/completed' => 'tasks#completed'
  
  resources :tasks
  resources :projects do
    resources :tasks, only: [:new]
  end
  resources :friendships, only: [:new, :create, :destroy]
  resources :comments, only: [:create, :destroy]
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: [:index, :show] do
    resources :projects, only: [:index]
  end

  authenticated :user do
    root 'projects#index', as: 'authenticated_root'
  end
  devise_scope :user do
    root 'devise/sessions#new'
  end

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  belongs_to :project
  has_many :comments, as: :commentable, dependent: :delete_all

  validates :title, presence: true
  validates :project, presence: true
  validates :completed, inclusion: [true, false]
  validates_date :due_date, on_or_after: lambda { Date.now } 

  def self.by_due_date(user)
    where(completed: false, user: user).order(due_date: :asc).limit(10)
  end

  def self.completed(user)
    where(completed: true, user: user).order(due_date: :asc)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :set_task, only: [:show, :edit, :update, :destroy]

    def index
        @tasks = Task.by_due_date(current_user)
    end

    def completed
        @tasks = Task.completed(current_user)
    end

    def show
        @comment = Comment.new
    end

    def new
        if params[:project_id]
            project = Project.find_by(id: params[:project_id])
            @task = project.tasks.build
        else
            @task = Task.new
            @projects = current_user.projects
        end
    end

    def create
        @task = Task.new(task_params)
        if @task.save
            flash[:success] = "Task has been added"
            redirect_to project_path(@task.project_id)
        else
            if params[:task][:nested_route]
                render :new
            else
                @task.project_id = nil
                @projects = current_user.projects 
                render :new
            end
        end
    end

    def edit
        @projects = current_user.projects
    end

    def update
        if @task.update(task_params)
            flash[:success] = "Task updated."
            redirect_to project_path(@task.project)
        else
            render :edit
        end
    end

    def destroy
        project = @task.project 
        @task.destroy
        redirect_to project_path(project)
    end

    private

    def set_task
        @task = Task.find_by(id: params[:id])
        if @task && !@task.project.users.include?(current_user) && @task.project.private
            flash[:error] = "You are not permitted to see that page!"
            redirect_to projects_path
        elsif !@task 
            flash[:error] = "No task found."
            redirect_to projects_path
        end
    end

    def task_params
        params.require(:task).permit(:title, :completed, :due_date, :user_id, :project_id)
    end
    
end

app/helpers/tasks_helper.rb
module TasksHelper

    def readable_due_date(object)
        object.due_date.strftime("%b %d, %Y")
    end
    
end

app/views/tasks/_task_form.html.erb
<%= form_for task do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.label :title %> 
  <%= f.text_field :title %> <br>
  <%= f.label :due_date %> 
  <%= f.date_field :due_date %> <br>
  <% if task.project_id %>
    <%= f.hidden_field :project_id, value: task.project_id %>
    <%= f.hidden_field :nested_route, value: true %>
  <% else %>
    <%= f.label :project_id, "Project" %>
    <%= f.collection_select :project_id, projects, :id, :title %> <br>
  <% end %>
  <%= f.submit %>
<% end %>

app/views/tasks/_task_list.html.erb
<ul>
    <% tasks.each do |task| %>
        <li><%= link_to task.title, task_path(task) %></li>
        <ul>
            <li>Due <%= readable_due_date task %></li>
            <li>In <%= task.project.title %></li>
            <li>Created by <%= task.user.full_name %></li>
        </ul>
    <% end %>
</ul>

app/views/tasks/completed.html.erb
<h3><%= current_user.full_name %>'s Completed Tasks </h3> <br>

<%= render partial: "task_list", locals: {tasks: @tasks} %>

app/views/tasks/edit.html.erb
<% if @task.errors.any? %>
  <div id="error_explanation">
    <h4><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h4>
 
    <ul>
    <% @task.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<h3>Edit <%= @task.title %></h3> <br>

<%= render partial: "task_form", locals: {task: @task, projects: @projects} %>

app/views/tasks/index.html.erb
<h3><%= current_user.full_name %>'s Upcoming Tasks </h3> <br>

<%= render partial: "task_list", locals: {tasks: @tasks} %>

<br><br> <%= button_to 'New Task', new_task_path, method: :get %> <br>

app/views/tasks/new.html.erb
<% if @task.errors.any? %>
  <div id="error_explanation">
    <h4><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h4>
 
    <ul>
    <% @task.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<% if @task.project_id %>
  <h3>New task for <%= @task.project.title %> </h3> <br>
<% else %>
  <h3>New Task</h3> <br>
<% end %>

<%= render partial: "task_form", locals: {task: @task, projects: @projects} %>

app/views/tasks/show.html.erb
<h3><%= @task.title %></h3> <br>
<p>This task was created by <%= link_to @task.user.full_name, user_projects_path(@task.user) %>.</p>

<h5>Details</h5>
<ul>
    <li>Due <%= readable_due_date @task %></li>
    <li>Part of the <%= link_to @task.project.title, project_path(@task.project) %> project.</li>
</ul>

<% if @task.completed %>
    <%= button_to "Mark as Incomplete", task_path(@task), method: :patch, params: { :"task[completed]" => false } %>
<% else %>
    <%= button_to "Mark as Completed", task_path(@task), method: :patch, params: { :"task[completed]" => true } %>
<% end %>
<%= button_to "Edit Task", edit_task_path(@task), method: :get %>
<%= button_to "Delete Task", task_path(@task), method: :delete %>

<%= render partial: "comments/comment", locals: { object: @task } %>