config/routes.rb
Rails.application.routes.draw do
  get '/tasks/completed' => 'tasks#completed'
  
  resources :tasks
  resources :projects do
    resources :tasks, only: [:new]
  end
  resources :friendships, only: [:new, :create, :destroy]
  resources :comments, only: [:create, :destroy]
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: [:index, :show] do
    resources :projects, only: [:index]
  end

  authenticated :user do
    root 'projects#index', as: 'authenticated_root'
  end
  devise_scope :user do
    root 'devise/sessions#new'
  end

end

app/models/project.rb
class Project < ApplicationRecord
    has_many :tasks, dependent: :delete_all
    accepts_nested_attributes_for :tasks
    has_many :users, through: :tasks
    has_many :comments, as: :commentable, dependent: :delete_all
    
    validates :title, presence: true
    validates :private, inclusion: [true, false]

    def incomplete_tasks
        tasks.where(completed: false).order(due_date: :asc)
    end

    def completed_tasks
        tasks.where(completed: true).order(due_date: :asc)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_action :set_project, only: [:show, :edit, :update, :destroy]


    def index
        if params[:user_id]
            @user = User.find_by(id: params[:user_id])
            @projects = @user.public_projects
        else
            @user = current_user
            @projects = @user.projects.uniq
        end
    end

    def show
        @comment = Comment.new
    end

    def new
        @project = Project.new
        @project.tasks.build
    end

    def create
        @project = Project.create(project_params)
        if @project.save
            flash[:success] = "Your project was created."
            redirect_to project_path(@project)
        else
            render :new
        end
    end

    def edit
    end

    def update
        if @project.update(project_params)
            flash[:success] = "Your project has been updated."
            redirect_to project_path(@project)
        else
            render :edit 
        end
    end

    def destroy
        @project.destroy
        redirect_to projects_path
    end

    private

    def set_project
        @project = Project.find_by(id: params[:id])
        if @project && !@project.users.include?(current_user) && @project.private 
            flash[:error] = "You are not permitted to see that page!"
            redirect_to projects_path
        elsif !@project
            flash[:error] = "No project found."
            redirect_to projects_path
        end
    end

    def project_params
        params.require(:project).permit(
            :title,
            :private,
            tasks_attributes: [
                :user_id,
                :title,
                :due_date
            ]
        )
    end
    
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/edit.html.erb
<% if @project.errors.any? %>
  <div id="error_explanation">
    <h4><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h4>
 
    <ul>
    <% @project.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<h3>Edit <%= @project.title %> </h3> <br>

<%= form_for @project do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %> <br>
  <%= f.label :private, "Private?*" %> 
  <%= f.check_box :private, checked: false, unchecked: true %> <br>
  <%= f.submit %>
<% end %>

app/views/projects/index.html.erb
<h3><%= @user.full_name %>'s Projects </h3><br>

<% @projects.each do |project| %>
    <h5><%= link_to project.title, project_path(project) %></h5>
    <%= render partial: "tasks/task_list", locals: {tasks: project.incomplete_tasks} %>
<% end %>

<%= button_to 'New Project', new_project_path, method: :get %>
<%= button_to 'New Task', new_task_path, method: :get %>

app/views/projects/new.html.erb
<% if @project.errors.any? %>
  <div id="error_explanation">
    <h4><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h4>
 
    <ul>
    <% @project.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<h3>New Project</h3> <br>

<%= form_for @project do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %> <br>
    <%= f.label :private, "Private?" %> 
    <%= f.check_box :private, checked: false, unchecked: true %> <br>

    <%= f.fields_for :tasks do |task| %>
        <div>Make sure to add a task to get your project started!</div>
        <%= task.hidden_field :user_id, value: current_user.id %> 
        <%= task.label :title %>
        <%= task.text_field :title %> <br>
        <%= task.label :due_date %> 
        <%= task.date_field :due_date %> <br>
    <% end %>

    <%= f.submit %>
<% end %>

app/views/projects/show.html.erb
<h3 class="title"><%= @project.title %></h3> <br>

<h5>Tasks</h5>
<%= render partial: "tasks/task_list", locals: {tasks: @project.incomplete_tasks} %> <br>

<% if @project.completed_tasks.count > 0 %>
    <h5>Completed Tasks</h5>
    <%= render partial: "tasks/task_list", locals: {tasks: @project.completed_tasks} %> <br>
<% end %>

<%= button_to "Edit This Project", edit_project_path(@project), method: :get %>
<%= button_to 'New Task', new_project_task_path(@project), method: :get %>
<%= button_to "Delete Project", project_path(@project), method: :delete %>

<%= render partial: "comments/comment", locals: { object: @project } %>