config/routes.rb
Rails.application.routes.draw do
  get '/tasks/completed' => 'tasks#completed'
  
  resources :tasks
  resources :projects do
    resources :tasks, only: [:new]
  end
  resources :friendships, only: [:new, :create, :destroy]
  resources :comments, only: [:create, :destroy]
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: [:index, :show] do
    resources :projects, only: [:index]
  end

  authenticated :user do
    root 'projects#index', as: 'authenticated_root'
  end
  devise_scope :user do
    root 'devise/sessions#new'
  end

end

app/views/layouts/_navigation.html.erb
<div>
<nav class="nav">
    <% if user_signed_in? %>
        <ul class="nav">
            <li><%= link_to 'Projects', projects_path, class: "nav-link" %></li>
            <li><%= link_to 'Tasks', tasks_path, class: "nav-link" %></li>
            <li><%= link_to 'Completed Tasks', tasks_completed_path, class: "nav-link" %></li>
            <li><%= link_to 'Friends', users_path, class: "nav-link" %></li> <br>
            <li><%= link_to 'Edit Profile', edit_user_registration_path, class: "nav-link" %></li>
            <li><%= link_to 'Sign Out', destroy_user_session_path, method: "delete", class: "nav-link" %></li>
        </ul>
    <% end %>
</nav>

<div class="search">
    <% if user_signed_in? %>
            <%= form_tag(users_path, method: :get) do %>
                <%= text_field_tag(:search, params[:search]) %>
                <%= submit_tag ("Search Users") %>
            <% end %>
    <% end %>
</div>

<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "WellDone" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Get Things Done Well" %>">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="wrapper">
    <header>
      <%= render 'layouts/navigation' %>
    </header>

    <% flash.each do |type, msg| %>
      <div>
        <%= msg %>
      </div> <br>
    <% end %>


    <%= yield %>
    </div>
  </body>
</html>